### ISSUE TITLE
can not deal issue id when adding a subtask

### ISSUE THREAD

**Issue by kaikuo** [VoronyukM/issue_id#2]
When add a subtask, the parent task id will default be in issue_id format (PROJECT_KEYWORD+Number)，
can we change the parent issue id to origin id when creating new task?

**Comment by VoronyukM** [comment]
You have the error like that:
http://projects.andriylesyuk.com/issues/ISSUE-4
?

> can we change the parent issue id to origin id when creating new task?

I think it is better to teach the plugin to recognize both formats (origin id and PROJECT_KEYWORD+Number) during subtask creation

**Comment by kaikuo** [comment]
correctly right!
I work mainly on embedded SW, and I'm a freshman on rubys, 
I try to do sth. like this on lib/issue_ids_controller_patch.rb, "try to replace parent_issue_id value from issue_id format to origin id format", but it failes, do you have any ideas?

```
    def build_new_issue_from_params_with_full_ids
        if params[:copy_from] && params[:copy_from].include?('-')
            issue = Issue.find(params[:copy_from])
            params[:copy_from] = issue.id.to_s if issue
        end
        if params[:issue]
            issue = params[:issue]
            if issue[:parent_issue_id]
                raw_id = Issue.find_by_id(issue[:parent_issue_id])
                params[:issue][:parent_issue_id] = raw_id
                Rails.logger.info "Find #raw_id"
            end
        end

        build_new_issue_from_params_without_full_ids
    end
```
